blog/urls.py
from . import views
from django.views import View
from django.urls import path 

urlpatterns = [
        path('blog-post-list', views.BlogListView.as_view(), name='blog-post-list'),
        path('<slug:slug>', views.BlogDetailView.as_view(), name='detail_view')

]

contact/urls.py
from . import views
from django.views import View
from django.urls import path

urlpatterns = [
        path('contact_us', views.ContactUs, name='contact_us'),
        path('contact_us_post', views.ContactUsPost.as_view(), name='contact_us_post'),

]

enigma_machine/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("bookings.urls"), name="bookings-urls"),
    path('accounts/', include('allauth.urls')),
    path('user_profiles/', include('user_profiles.urls')),
    path('contact/', include('contact.urls')),
    path('blog/', include('blog.urls')),
    path('rooms/', include('rooms.urls')),
]

blog/models.py
from django.db import models
from cloudinary.models import CloudinaryField 


class BlogPost(models.Model):
    blog_title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    blog_image = CloudinaryField('image', default='placeholder')
    blog_blurb = models.TextField(blank=True)
    blog_content = models.TextField()
    posted_date = models.DateTimeField(auto_now=True)
    meta_tags = models.CharField(max_length=255, blank=True)

    class Meta:
        ordering = ["-posted_date"]

    def __str__(self):
        return self.blog_title

contact/models.py
from django.db import models
from django.core.validators import RegexValidator

class ContactUs(models.Model):
    inquiry_id = models.AutoField(primary_key=True)
    inquiry_name = models.CharField(max_length=75)
    inquiry_email = models.EmailField()
    phone_number = models.CharField(max_length=14)
    created_date = models.DateTimeField(auto_now_add=True)
    inquiry_message = models.TextField()

    class Meta:
        ordering = ['-created_date'] 

    def __str__(self):
        return f"{self.inquiry_name} Iquiry Date: {self.created_date}"

contact/forms.py
from django import forms
from .models import ContactUs

class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = (
            'inquiry_name',
            'inquiry_email',
            'phone_number',
            'inquiry_message',
        )
        widgets = {
            'inquiry_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Name'}),
            'inquiry_email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Email'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Your Phone Number'}),
            'inquiry_message': forms.Textarea(attrs={'class': 'form-control', 'rows': 6, 'placeholder': 'What is your Question?'}),
        }

        def __init__(self, *args, **kwargs):
                super().__init__(*args, **kwargs)
                self.fields['inquiry_name'].widget.attrs.update({'autofocus': True})
                self.fields['inquiry_email'].widget.attrs.update({'autofocus': True})
                self.fields['phone_number'].widget.attrs.update({'autofocus': True})
                self.fields['inquiry_message'].widget.attrs.update({'autofocus': True})



        def clean(self):
            cleaned_data = super().clean()
            name = cleaned_data.get('inquiry_name')
            emails = cleaned_data.get('inquiry_email')
            phone = cleaned_data.get('phone_number')
            message = cleaned_data.get('inquiry_message')

            if not name:
                self.add_error('name', 'Please enter your name.')
            if not emails:
                self.add_error('emails', 'Please enter your email.')
            if not phone:
                self.add_error('phone', 'Please enter your phone number.')
            if not message:
                self.add_error('message', 'Please enter your message.')

            return cleaned_data        

contact/views.py
from django.shortcuts import render
from django.contrib import messages
from .forms import ContactUsForm
from django.views import View


# Create your views here.
def ContactUs(request):
    template = 'contact.html'
    form = ContactUsForm()

    context = {
        'form': form
    }

    return render(request, template, context)

class ContactUsPost(View):

    def get(self, request):
        return render(request, 'contact.html')

    def post(self, request):
        new_form = ContactUsForm()
        contact_form = ContactUsForm(data=request.POST)
        if contact_form.is_valid():
            form = contact_form.save(commit=False)
            form.save()
            messages.success(request, "Message has been sent")
            return render(request, 'contact.html', {'form': new_form})
        else:
            new_form = ContactUs(request)
            messages.error(request, "Error: Please try again")
            return render(request, 'contact.html', {'form': new_form})

templates/account_bookings.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    <!-- <h1>{{ reservations }}</h1>
    <h1>{{ current_date }}</h1>
    <h1>{{res}}</h1> -->
    {% for reservation in reservations %}
    {% if current_date > reservation|first %}
        <h2>Past</h2>
                <h1>{{ reservation.0}} {{ reservation.1}} {{ reservation.2}}</h1>
    {% else %}
        <form method="post" action="{% url 'booking_edit_selection' %}">
        {% csrf_token %}
            <h2>Future</h2>
                <h1>{{ reservation.0}} {{ reservation.1}} {{ reservation.2}}</h1><button type="submit">Edit/Delete</button>
                <input type="hidden" name="res_id" value="{{reservation.3}}">
        </form>
    {% endif %}
    {% endfor %}
    <a href="{% url 'account_overview' %}">Return to Account</a>
{% endblock %}

templates/account_page.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
    <form method="post" action="account_update_view">
        {% csrf_token %}
        <h1>Account Page</h1>
        <h1>Username: {{ username }}</h1>
        <input type="hidden" name="username" value="">
        <h1>Customer Name: {{ first_name }} {{ last_name }}</h1>
        <input type="hidden" name="first_name" value="">
        <input type="hidden" name="last_name" value="">
        <h1>Email Address: {{ email }}</h1>
        <input type="hidden" name="email" value="">
        <input type="hidden" name="user_id" value="{{user_id}}">
        <h3>Need to update your account information?</h3>
        <button type=submit>Update Here</button>
    </form>
    <form action="{% url 'account_bookings'%}">
        <button type="submit">Reservations</button>
        <input type="hidden" name="username" value="">
        <input type="hidden" name="first_name" value="">
        <input type="hidden" name="last_name" value="">
        <input type="hidden" name="email" value="">
        <input type="hidden" name="user_id" value="{{user_id}}">
    </form>
    Don't forget to tell others about your time with us!
    Review Here! 
    <a href="www.facebook.com" target="_blank" aria-label="Opens link to Facebook.com in another window">Facebook</a>
    <a href="www.tripadvisor.com" target="_blank" aria-label="Opens link to Tripadvisor.com in another window">TripAdvisor</a>
    <a href="www.yelp.com" target="_blank" aria-label="Opens link to Yelp.com in another window">Yelp</a>
    <a href="www.google.com" target="_blank" aria-label="Opens link to Google.com in another window">Google</a>

{% endblock %}

templates/account_page_edit.html
{% extends "base.html" %}
{% block content %}
<form method="POST" action="{% url 'account_update_post'%}">
    {% csrf_token %}
    <h1>Edit Account Information</h1>
    <input type="text" name="new_username" value="{{ username }}">
    <input type="text" name="new_first_name" value="{{ first_name }}">
    <input type="text" name="new_last_name" value="{{ last_name }}">
    <input type="text" name="new_email" value="{{ email }}">
    <input type="hidden" name="user_id" value="{{user_id}}">
    <button type="submit">Update Now</button>
</form>
<form method='post' action="{% url 'delete_account' %}">
    {% csrf_token %}
        <button type="submit">Request Account Deletion</button>
        <input type="hidden" name="user_id" value="{{user_id}}">

    </form>
{% endblock %}
    

templates/blog_post_detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ blog.blog_title }}</h1>
<h3>{{ blog.blog_blurb}}</h3>
<p>{{ blog.blog_content }}</p>
{% endblock %}

templates/blog_posts.html
{% extends "base.html" %}
{% block content %}
<h1>Blog Posts</h1>
{% if blogpost_list%}
  {% for blogpost in blogpost_list %}
    <a href="{% url 'detail_view' blogpost.slug %}">
      <h2>{{ blogpost.blog_title }}</h2>
      <h2>{{ blogpost.slug }}</h2>
      <h2>{{ blogpost.blog_content}}</h2>
    </a>
  {% endfor %}
{% else %}
  <h1>No blog posts are available</h1>
{% endif %}
{% endblock %}

templates/contact.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<section id="get-started" class="get-started section-bg">
    <div class="container">

      <div class="row justify-content-between gy-4">

        <div class="col-lg-6 d-flex align-items-center" data-aos="fade-up">
          <div class="content">
            <h3>Our Location</h3>
            <h5>Address:</h5>
            <p>1234 Mockingbird Lane, Suite 567<br>
              Springfield, MA 01101</p>
            <h5>Phone:</h5>
            <p>(555) 555-1234</p>
            <h5>Email:</h5>
            <p>info@enigmamachine.com</p>
          </div>
        </div>

        <div class="col-lg-5" data-aos="fade">
          <form action="{% url 'contact_us_post' %}" method="post">
            {% csrf_token %}
            <h3>Get a quote</h3>
            <p>Vel nobis odio laboriosam et hic voluptatem. Inventore vitae totam. Rerum repellendus enim linead sero park flows.</p>
            <div class="row gy-3">
                <div class="col-md-12">
                   <div class="form-control">{{ form.inquiry_name }}</div>
                </div>

                <div class="col-md-12 ">
                  <div class="form-control">{{ form.inquiry_email }}</div>
                </div>

                <div class="col-md-12">
                  <div class="form-control">{{ form.phone_number }}</div>
                </div>

                <div class="col-md-12">
                  <div class="form-control">{{ form.inquiry_message }}</div>
                </div>
                <button type="submit">Contact Us!</button>
              </div>

            </div>
          </form>
        </div><!-- End Quote Form -->

      </div>

    </div>
  </section><!-- End Get Started Section -->
{% endblock %}

templates/date_choice.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<form mehtod="POST" action="{% url 'reservation' %}">
    {% csrf_token %}
    <input type="date" name="selected_date">
    <button type="submit">Choose Date</button>
</form>

{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% block content %}
{% endblock %}

templates/posted.html
{% extends "base.html" %}
{% block content %}
{{ cart }}
    <h1>Success</h1>
{% endblock %}

templates/reservation.html
{% extends "base.html" %}
{% block content %}

<form method="GET" action="{% url 'reservation' %}?selected_date={{ selected_date }}">
  {% csrf_token %}
  <input type="date" name="selected_date" value="{{specific_date}}"><button type="submit">Select Date</button>{{specific_date}}
  </form>
  <div class="d-flex flex-row">
      {% for result in results %}
          <div class="flex-grow-1">
                  <table>
                      <thead>
                          {% for key, values in result.items %}
                          <tr>
                              <th>{{key}}</th>
                          </tr>
                      </thead>
                      <tbody>
                          {% for value in values %}
                              <tr>
                              <td id="iterate-{{ forloop.counter }}">
                              <form method="POST">
                                  {% csrf_token %}
                                  <input type="hidden" name="key" value="{{ key }}">
                                  <input type="hidden" name="value" value="{{ value }}">
                                  <input type="hidden" name="specific_date" value="{{ specific_date }}">
                                  <button type="submit" class="my-button btn btn-primary text-white" data-key="{{ key }}" data-value="{{ value }}">{{ value }}</button>
                              </form>
                          </td>
                      </tr>
                      {% endfor %}
                      {% endfor %}
              </tbody>
          </table>
      {% endfor %} 
  </div>
  
  
  
  {% if cart %}
      <h2>Shopping Cart</h2>
      <ul>
          {% for item in cart %}
          <li>{{ item.key }}: {{ item.value }} ({{ item.specific_date }}) 
          <form method="POST">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger" name="delete-item" value="{{ item.key }}|{{ item.value }}|{{ item.specific_date }}">Delete</button>
          </form>
          </li>        
          {% endfor %}
      </ul>
      <form method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger" name="delete-all" value="true">Delete All Items</button>
      </form>
      <form form action="{% url 'booking'%}?cart={{ cart }}" method="post"> 
          {% csrf_token %}
          <input type="hidden" name="cart" value={{cart}}>
          <button type="submit">Continue to Booking</button>
      </form>
  {% endif %}
  

<script>
  // Get all list items using a CSS selector
  var items = document.querySelectorAll(".my-button");

  // Loop through each list item
  items.forEach(function(value) {
    // Check if the inner HTML of the item is "501"
    if (value.innerHTML != "45") {
      // If it is, change the inner HTML to "888"
      value.innerHTML = "Available";
    } else if (value.innerHTML === "45") {
      value.innerHTML = "Unavailable"
      value.disabled = true
    }
  });
</script>  
{% endblock %}

templates/reservation_edit.html
{% extends "base.html" %}
{% block content %}
<form method = POST action="{% url 'update_booking' %}">
    {% csrf_token %}
        <input type="hidden" name="res_id" value="{{res_id}}">
        <input type="date" name="picked_date" value="{{picked_date}}"><button type="submit">View Available Games</button>
</form>
<form method = POST action="{% url 'delete_booking' %}">
    {% csrf_token %}
        <input type="hidden" name="res_id" value="{{res_id}}">
        <button type="submit">Delete Booking</button>
</form>
{% for result in results %}
    {% for key, values in result.items %}
        {{key}}
        {% for value in values %}
            {% if value != 45 %}
                <form method="POST" action="{% url 'post_update'%}">
                    {% csrf_token %}
                    <input type="hidden" name="key" value="{{ key }}">
                    <input type="hidden" name="value" value="{{ value }}">
                    <input type="hidden" name="selected_date" value="{{ selected_date }}">
                    <input type="hidden" name="res_id" value="{{res_id}}">
                    <button type="submit" class="my-button btn btn-primary text-white" data-key="{{ key }}" data-value="{{ value }}">{{ value }}</button>
                </form>
            {% endif %}

        {% endfor %}
    {% endfor %}
{% endfor %} 
{% endblock %}

templates/room_list.html
{% extends "base.html" %}
{% block content %}
{% for room in room_list %}
<h1>{{ room.room_name }}</h1>
<p>{{ room.room_description }}</p>
{% endfor %}
{% endblock %}

templates/selected_reservation.html
{% extends "base.html" %}
{% block content %}

<h1>Hello</h1>
<form method="POST" form action="{% url 'posted' %}?data={{ data }}">
{{data}}
<input type="hidden" name="data" value="{{data}}">
    {% for booking in data %}
        <h3>Room: {{ booking.key }}</h3>
        <input type="hidden" name="room" value="{{ booking.key }}">
        <h3>Time: {{ booking.value }}</h3>
        <input type="hidden" name="time" value="{{ booking.value }}">
        <h3>Date: {{ booking.specific_date }}</h3>
        <input type="hidden" name="date" value="{{ booking.specific_date }}">
        <h3>Group Size:<input name="number" type="number" min="2" max="7"></h3>
    {% endfor %}
        <input type="text" name="name" value="{{ first_name}} {{ last_name }}">
        <input type="text" name="email" value="{{ email }}">
        <input type="text" name="phone">
        <input type="number" name="price" min="300">
        <textarea name="comment" style="resize:none;"></textarea>
    {% csrf_token %}

    <button type="submit">Complete Booking</button> 
</form>
  
  <script>
    // Get all list items using a CSS selector
    var items = document.querySelectorAll(".my-button");
  
    // Loop through each list item
    items.forEach(function(value) {
      // Check if the inner HTML of the item is "501"
      if (value.innerHTML != "45") {
        // If it is, change the inner HTML to "888"
        value.innerHTML = "Available";
      } else if (value.innerHTML === "45") {
        value.innerHTML = "Unavailable"
        value.disabled = true
      }
    });
  </script>  
{% endblock %}